[package]
name = "fsqlite-ext-fts5"
version = "0.3.4"
description = "FTS5 full-text search extension"
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
fsqlite-types = { workspace = true }
fsqlite-error = { workspace = true }
fsqlite-func = { workspace = true }
smallvec = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
asupersync = { workspace = true }
rusqlite = { workspace = true }

[lints]
workspace = true
