#!/usr/bin/env bash
#
# bd-ohk1x: fail when an fsqlite-e2e integration test exists that no CI
# workflow ever runs.
#
# WHY THIS EXISTS
#
# `crates/fsqlite-e2e/tests/*.rs` holds the differential, conformance, and
# corruption suites. Two independent mechanisms mean most of them never execute:
#
#   1. concurrent-platform-matrix.yml runs `cargo test -p fsqlite-e2e --no-run`
#      (build only), then executes an explicit `--test <name>` allowlist.
#   2. unit-test-shard-matrix.yml runs `cargo test -p "${crate}" --lib` for
#      every crate but fsqlite-cli. `fsqlite-e2e` is in that shard's crate list,
#      but `--lib` never touches `tests/`.
#
# So "fsqlite-e2e is covered by two workflows" is simultaneously true and
# misleading. A new `tests/*.rs` proving a correctness property will compile in
# CI and never run unless someone also edits a workflow allowlist -- and nothing
# told them to.
#
# WHAT THIS GATE DOES, AND DELIBERATELY DOES NOT DO
#
# It does NOT demand that every test be wired in. Most are unrun today, and
# failing on all of them would make the gate permanently red and therefore
# ignored. Instead it FREEZES the current state via an explicit baseline and
# fails only on drift:
#
#   * a test file that is neither named by a workflow nor listed in the baseline
#     -> NEW un-run test. Fail: wire it in, or add it to the baseline with intent.
#   * a baseline entry that no longer exists on disk -> stale. Fail: clean it up.
#   * a baseline entry that a workflow now names -> it runs. Fail: it should be
#     removed from the baseline so the baseline keeps meaning "does not run".
#
# The point is that the allowlist stops drifting silently. A drifting allowlist
# is worse than an honest small one, because it reads as coverage.
#
# Usage:
#   scripts/ci_e2e_test_discovery_gate.sh            # check (exit 1 on drift)
#   scripts/ci_e2e_test_discovery_gate.sh --write    # regenerate the baseline
set -uo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root" || exit 2

tests_dir="crates/fsqlite-e2e/tests"
workflows_dir=".github/workflows"
baseline=".github/e2e-tests-not-run-in-ci.txt"
mode="${1:-check}"

if [ ! -d "$tests_dir" ]; then
  echo "::error::$tests_dir not found (run from the repo, or the crate moved)"
  exit 2
fi
if [ ! -d "$workflows_dir" ]; then
  echo "::error::$workflows_dir not found"
  exit 2
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# Every integration-test target name in the crate.
#
# Enumerate TRACKED files, not whatever is on disk. A shared developer checkout
# routinely carries untracked scratch tests (e.g. the `zz_*` rch probes), and
# generating the baseline from `find` bakes those transient names in — then the
# gate fails on a clean CI checkout where they do not exist. Ask git instead, and
# fall back to `find` only outside a work tree (e.g. a source tarball).
if git -C . rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git -C . ls-files "$tests_dir/*.rs" \
    | xargs -r -n1 basename \
    | sed 's/\.rs$//' | LC_ALL=C sort -u > "$tmp/all"
else
  find "$tests_dir" -maxdepth 1 -name '*.rs' -type f -printf '%f\n' \
    | sed 's/\.rs$//' | LC_ALL=C sort -u > "$tmp/all"
fi

# Every test target any workflow names. `--test foo` and `--test=foo` both count.
grep -rhoE -- '--test[= ][A-Za-z0-9_]+' "$workflows_dir" 2>/dev/null \
  | sed -E 's/^--test[= ]//' | LC_ALL=C sort -u > "$tmp/named"

LC_ALL=C comm -23 "$tmp/all" "$tmp/named" > "$tmp/unrun"

if [ "$mode" = "--write" ]; then
  {
    echo "# bd-ohk1x baseline: fsqlite-e2e integration tests that NO CI workflow runs."
    echo "#"
    echo "# Generated by scripts/ci_e2e_test_discovery_gate.sh --write"
    echo "# Do not hand-sort; regenerate instead."
    echo "#"
    echo "# Every name here compiles in CI and never executes. That is a coverage"
    echo "# gap, not an approval -- shrinking this file is the goal. Removing a"
    echo "# name requires actually wiring the test into a workflow."
    cat "$tmp/unrun"
  } > "$baseline"
  echo "wrote $baseline ($(grep -cv '^#' "$baseline") entries)"
  exit 0
fi

if [ ! -f "$baseline" ]; then
  echo "::error::$baseline is missing; regenerate with: $0 --write"
  exit 1
fi

grep -v '^#' "$baseline" | grep -v '^[[:space:]]*$' | LC_ALL=C sort -u > "$tmp/baseline"

failed=0

# 1. New un-run tests: on disk, not named by any workflow, not in the baseline.
LC_ALL=C comm -23 "$tmp/unrun" "$tmp/baseline" > "$tmp/new_unrun"
if [ -s "$tmp/new_unrun" ]; then
  failed=1
  count=$(wc -l < "$tmp/new_unrun")
  echo "::error::${count} fsqlite-e2e integration test(s) exist that no workflow runs and that are not in the baseline."
  echo "         They will COMPILE in CI and never EXECUTE, so they gate nothing."
  while IFS= read -r t; do
    echo "::error file=${tests_dir}/${t}.rs::'${t}' is never run by any workflow. Add '--test ${t}' to a workflow, or add it to ${baseline} if that is intended."
  done < "$tmp/new_unrun"
fi

# 2. Stale baseline entries: listed as un-run, but the file is gone.
LC_ALL=C comm -13 "$tmp/all" "$tmp/baseline" > "$tmp/ghosts"
if [ -s "$tmp/ghosts" ]; then
  failed=1
  while IFS= read -r t; do
    echo "::error file=${baseline}::'${t}' is in the baseline but ${tests_dir}/${t}.rs does not exist. Remove the stale entry."
  done < "$tmp/ghosts"
fi

# 3. Baseline entries that now run: the baseline must keep meaning "does not run".
LC_ALL=C comm -12 "$tmp/baseline" "$tmp/named" > "$tmp/now_running"
if [ -s "$tmp/now_running" ]; then
  failed=1
  while IFS= read -r t; do
    echo "::error file=${baseline}::'${t}' is now named by a workflow, so it is no longer un-run. Remove it from the baseline."
  done < "$tmp/now_running"
fi

total=$(wc -l < "$tmp/all")
named=$(LC_ALL=C comm -12 "$tmp/all" "$tmp/named" | wc -l)
unrun=$(wc -l < "$tmp/unrun")
echo "fsqlite-e2e integration tests: ${total} total, ${named} run by CI, ${unrun} never run."

if [ "$failed" -eq 0 ]; then
  echo "e2e test-discovery gate: OK (no drift against ${baseline})"
fi
exit "$failed"
